*&---------------------------------------------------------------------*
*&  VIEW
*&---------------------------------------------------------------------*

CLASS REPORT_VIEW DEFINITION.

  PUBLIC SECTION.

    DATA:SALV_ALV      TYPE REF TO CL_SALV_TABLE,
         R_DOUBLECLICK TYPE REF TO   CL_SALV_EVENTS_TABLE.

    METHODS: INITIALIZATION,
      SELECTION_SCREEN_0,
      SELECTION_SCREEN IMPORTING MODEL TYPE REF TO REPORT_MODEL,
      END_OF_SELECTION IMPORTING MODEL TYPE REF TO REPORT_MODEL,
      CL_SALV_ALV      IMPORTING MODEL TYPE REF TO REPORT_MODEL,
      SET_TOOLBAR.

ENDCLASS.


*--------------------------------------------------------------------*
"Função de double click para exibir os detalhes do cliente selecionado




CLASS REPORT_VIEW IMPLEMENTATION.

  METHOD INITIALIZATION.

  ENDMETHOD.

  METHOD SELECTION_SCREEN_0.

  ENDMETHOD.

  METHOD SELECTION_SCREEN.

  ENDMETHOD.

  METHOD END_OF_SELECTION.
    ME->CL_SALV_ALV( MODEL ).
  ENDMETHOD.

  METHOD CL_SALV_ALV.
    CL_SALV_TABLE=>FACTORY(
      IMPORTING R_SALV_TABLE = SALV_ALV
      CHANGING  T_TABLE      = MODEL->LT_VBAK
    ).

    R_DOUBLECLICK = SALV_ALV->GET_EVENT( ).
    SET HANDLER MODEL->DOUBLE_CLICK FOR R_DOUBLECLICK.

    ME->SET_TOOLBAR( ).

    SALV_ALV->DISPLAY( ).
   ENDMETHOD.

  METHOD SET_TOOLBAR.
    DATA:FUNCTIONS     TYPE REF TO CL_SALV_FUNCTIONS_LIST.

    FUNCTIONS = SALV_ALV->GET_FUNCTIONS( ).
    FUNCTIONS->SET_ALL( ).
  ENDMETHOD.


ENDCLASS.
