REPORT ZTR_AI_003.

TABLES: SFLIGHT.

DATA: LT_SFLIFHT   TYPE TABLE OF SFLIGHT,
      CL_TABLE     TYPE REF TO CL_SALV_TABLE.


SELECTION-SCREEN: BEGIN OF BLOCK BLOCO WITH FRAME TITLE TEXT-001.

*Select Options para nome da Companhia de vôo
SELECT-OPTIONS: S_CARRID FOR SFLIGHT-CARRID.
SELECTION-SCREEN SKIP.

*Parameter para filtro de datas
PARAMETER: P_DATA TYPE SY-DATUM.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN: END OF BLOCK BLOCO.

"Roda na Execução do Programa
START-OF-SELECTION.
  PERFORM NOME_COMP.
  PERFORM P_DATA.
  PERFORM DISPLAY.

"Form para impressão dos dados
FORM DISPLAY.
  CALL METHOD CL_SALV_TABLE=>FACTORY"Método estático.
    EXPORTING
      LIST_DISPLAY = ABAP_TRUE "Exibir em formato de lista
    IMPORTING
      R_SALV_TABLE = CL_TABLE
    CHANGING
      T_TABLE     = LT_SFLIFHT.

  PERFORM FEED_FUNCTIONS.

  CALL METHOD CL_TABLE->DISPLAY.
ENDFORM.

"Adiciona todas as opções do ALV
FORM FEED_FUNCTIONS.
  DATA: LC_FUNCTIONS TYPE REF TO CL_SALV_FUNCTIONS.

  LC_FUNCTIONS = CL_TABLE->GET_FUNCTIONS( ).
  LC_FUNCTIONS->SET_ALL( 'X' ). "set_all habilita todas as funcionalidades
  "('x') ou abap_true significam a mesma coisa.
ENDFORM.

"Filtrando os dados de nome de Companhia na tabela sflight
FORM NOME_COMP.

  SELECT *
   FROM SFLIGHT
   INTO TABLE LT_SFLIFHT
   WHERE SFLIGHT~CARRID IN S_CARRID.

ENDFORM.

"Filtrando os dados do parameter data.
FORM P_DATA.
    SELECT *
    FROM SFLIGHT
    INTO TABLE LT_SFLIFHT
    WHERE SFLIGHT~FLDATE = P_DATA.
ENDFORM.
