REPORT ZTR_AI_TESTES.

"Declarando classe:
CLASS ANIMAL DEFINITION.
  PUBLIC SECTION.
    "Atributos:
    DATA: COR_PELE TYPE STRING.

    "Métodos:
    METHODS: COMER.
ENDCLASS.

"Classe pai
CLASS ANIMAL IMPLEMENTATION.
  METHOD COMER.
    WRITE: 'Animal se alimentou!', /.
  ENDMETHOD.
ENDCLASS.

CLASS AVES DEFINITION INHERITING FROM ANIMAL. "Classe Aves herda da Classe animal.

  PUBLIC SECTION.

    METHODS: VOAR.
             COMER REDEFINITION "Permite alterar o comportamento de determinado método.

ENDCLASS.

CLASS AVES IMPLEMENTATION.

  METHOD VOAR.
    WRITE: 'Aves podem voar!', /.
  ENDMETHOD.

  METHOD COMER.
  WRITE: 'A ave se alimentou'.
  ENDMETHOD.

ENDCLASS.

DATA: CL_ANIMAL1 TYPE REF TO ANIMAL,
      CL_ANIMAL2 TYPE REF TO ANIMAL,
      CL_AVE     TYPE REF TO AVES.

INITIALIZATION.
  CREATE OBJECT CL_ANIMAL1.
  CREATE OBJECT CL_ANIMAL2.
  CREATE OBJECT CL_AVE.

  CL_ANIMAL1->COR_PELE = 'PRETA'.
  WRITE: 'Cor do animal 1: ', CL_ANIMAL1->COR_PELE.
  CL_ANIMAL1->COMER( ).


  CL_ANIMAL2->COR_PELE = 'MARROM'.
  WRITE: 'Cor do animal 2: ', CL_ANIMAL2->COR_PELE.
  CL_ANIMAL2->COMER( ).


  CL_AVE->COR_PELE = 'BRANCA'.
  WRITE: 'COR DA AVE: ', CL_AVE->COR_PELE.
  CL_AVE->VOAR( ).
