TABLES: VBAK, LFA1, VBPA.

SELECTION-SCREEN BEGIN OF BLOCK BLOCO1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: S_LIFNR FOR LFA1-LIFNR,
                S_ERDAT FOR VBAK-ERDAT.

SELECTION-SCREEN END OF BLOCK BLOCO1.
 
