
*--------------------------------------------------------------------*
**Model
*--------------------------------------------------------------------*

CLASS REPORT_MODEL DEFINITION.

  PUBLIC SECTION.

    METHODS: START_OF_SELECTION,
      GET_TABLE.

ENDCLASS.

CLASS REPORT_MODEL IMPLEMENTATION.

  METHOD START_OF_SELECTION.
    ME->GET_TABLE( ).
  ENDMETHOD.


  METHOD GET_TABLE.

*--------------------------------------------------------------------*
**Seleciona o conteúdo das tabelas
*--------------------------------------------------------------------*

    SELECT REGION,
           CITY1,
           ADDRNUMBER
      UP TO 500 ROWS
      FROM ADRC
      INTO TABLE @DATA(TABLE_ADRC)
      WHERE REGION IN @S_REGION AND
            CITY1  IN @S_CITY1.

  CHECK TABLE_ADRC IS NOT INITIAL.


    SELECT ADRNR,
           KUNNR,
           REGIO
      UP TO 500 ROWS
      FROM KNA1
      INTO TABLE @DATA(TABLE_KNA1)
      FOR ALL ENTRIES IN @TABLE_ADRC
      WHERE ADRNR EQ @TABLE_ADRC-ADDRNUMBER.


    SELECT BLAND,
           BEZEI
      UP TO 500 ROWS
      FROM T005U
      INTO TABLE @DATA(TABLE_T005U)
      FOR ALL ENTRIES IN @TABLE_KNA1
      WHERE BLAND EQ @TABLE_KNA1-REGIO.


    SELECT KUNNR,
           ERDAT,
           VBELN
      UP TO 500 ROWS
      FROM VBAK
      INTO TABLE @DATA(TABLE_VBAK)
      FOR ALL ENTRIES IN @TABLE_KNA1
      WHERE KUNNR EQ @TABLE_KNA1-KUNNR
      AND ERDAT IN @S_ERDAT.


    SELECT VBELN,
           NETWR,
           BRGEW
      UP TO 500 ROWS
      FROM VBAP
      INTO TABLE @DATA(TABLE_VBAP)
      FOR ALL ENTRIES IN @TABLE_VBAK
      WHERE VBELN EQ @TABLE_VBAK-VBELN.


    SELECT VBELN,
           VBELV,
           ERDAT
      UP TO 500 ROWS
      FROM VBFA
      INTO TABLE @DATA(TABLE_VBFA)
      FOR ALL ENTRIES IN @TABLE_VBAP
      WHERE VBELV EQ @TABLE_VBAP-VBELN.


    SELECT VBELN
      UP TO 500 ROWS
      FROM LIKP
      INTO TABLE @DATA(TABLE_LIKP)
      FOR ALL ENTRIES IN @TABLE_VBFA
      WHERE VBELN EQ @TABLE_VBFA-VBELN.


    SELECT VBELN
      UP TO 500 ROWS
      FROM LIPS
      INTO TABLE @DATA(TABLE_LIPS)
      FOR ALL ENTRIES IN @TABLE_LIKP
      WHERE VBELN EQ @TABLE_LIKP-VBELN.


    SELECT TKNUM,
           VBELN
      UP TO 500 ROWS
      FROM VTTP
      INTO TABLE @DATA(TABLE_VTTP)
      FOR ALL ENTRIES IN @TABLE_LIPS
      WHERE VBELN EQ @TABLE_LIPS-VBELN.


    SELECT TKNUM
      UP TO 500 ROWS
      FROM VTTK
      INTO TABLE @DATA(TABLE_VTTK)
      FOR ALL ENTRIES IN @TABLE_VTTP
      WHERE TKNUM EQ @TABLE_VTTP-TKNUM.

**--------------------------------------------------------------------*
***Loop para unir as tabelas
**--------------------------------------------------------------------*

    LOOP AT TABLE_VBAP INTO DATA(STRUCT_VBAP).

      READ TABLE TABLE_VBFA INTO DATA(STRUCT_VBFA)   WITH KEY VBELV       = STRUCT_VBAP-VBELN.

      READ TABLE TABLE_LIKP INTO DATA(STRUCT_LIKP)   WITH KEY VBELN       = STRUCT_VBFA-VBELN.

      READ TABLE TABLE_LIPS INTO DATA(STRUCT_LIPS)   WITH KEY VBELN       = STRUCT_VBFA-VBELN.

      READ TABLE TABLE_VBAK INTO DATA(STRUCT_VBAK)   WITH KEY ERDAT       = STRUCT_VBFA-ERDAT.

      READ TABLE TABLE_VTTP INTO DATA(STRUCT_VTTP)   WITH KEY VBELN       = STRUCT_LIPS-VBELN.

      READ TABLE TABLE_VTTK INTO DATA(STRUCT_VTTK)   WITH KEY TKNUM       = STRUCT_VTTP-TKNUM.

      READ TABLE TABLE_KNA1 INTO DATA(STRUCT_KNA1)   WITH KEY KUNNR       = STRUCT_VBAK-KUNNR.

      READ TABLE TABLE_T005U INTO DATA(STRUCT_T005U) WITH KEY BLAND       = STRUCT_KNA1-REGIO.

      READ TABLE TABLE_ADRC INTO DATA(STRUCT_ADRC)   WITH KEY ADDRNUMBER  = STRUCT_KNA1-ADRNR.

      "Relatório da execução
      STRUCT-REGION       = STRUCT_ADRC-REGION.
      STRUCT-BEZEI        = STRUCT_T005U-BEZEI.
      STRUCT-CITY1        = STRUCT_ADRC-CITY1.
      STRUCT-BRGEW        = STRUCT_VBAP-BRGEW.
      STRUCT-NETWR        = STRUCT_VBAP-NETWR.
      STRUCT-ERDAT        = STRUCT_VBAK-ERDAT.

      "Pop up
      STRUCT_POP-TKNUM            = STRUCT_VTTK-TKNUM.
      STRUCT_POP-BRGEW            = STRUCT_VBAP-BRGEW.

      APPEND STRUCT TO TABLE.

      APPEND STRUCT_POP TO TABLE_POP.

    ENDLOOP.

  ENDMETHOD.

ENDCLASS.
