*&---------------------------------------------------------------------*
*&  Gerenciamento de eventos
*&---------------------------------------------------------------------*

CLASS REPORT_CONTROLLER DEFINITION.

  PUBLIC SECTION.

  DATA:VIEW  TYPE REF TO REPORT_VIEW,
       MODEL TYPE REF TO REPORT_MODEL.

  METHODS: INITIALIZATION,
           CONSTRUCTOR,
           SELECTION_SCREEN_0,
           SELECTION_SCREEN,
           START_OF_SELECTION,
           END_OF_SELECTION.


ENDCLASS.

CLASS REPORT_CONTROLLER IMPLEMENTATION.

  METHOD CONSTRUCTOR.

    CREATE OBJECT VIEW.
    CREATE OBJECT MODEL.

  ENDMETHOD.

  METHOD INITIALIZATION.
    ME->VIEW->INITIALIZATION( ).
  ENDMETHOD.

  METHOD SELECTION_SCREEN_0.
    ME->VIEW->SELECTION_SCREEN_0( ).
  ENDMETHOD.

  METHOD SELECTION_SCREEN.
    ME->VIEW->SELECTION_SCREEN( ).
  ENDMETHOD.

  METHOD START_OF_SELECTION.
    ME->MODEL->START_OF_SELECTION( ).
  ENDMETHOD.

  METHOD END_OF_SELECTION.
     ME->VIEW->END_OF_SELECTION( ).
  ENDMETHOD.


ENDCLASS.
