TABLES: VBAK, KNA1, VBAP.

SELECTION-SCREEN BEGIN OF BLOCK BL_01 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: S_KUNNR  FOR  KNA1-KUNNR,
                  S_ERDAT FOR  VBAK-ERDAT.
SELECTION-SCREEN END OF BLOCK BL_01.
