TABLES: VBAK, VBAP.

SELECTION-SCREEN BEGIN OF BLOCK BLOCO1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: S_ERDAT FOR VBAK-ERDAT,
                S_MATNR FOR VBAP-MATNR.

SELECTION-SCREEN END OF BLOCK BLOCO1.
