*--------------------------------------------------------------------*
**Select-options, parameters e tabelas transparentes que serão usadas.
*--------------------------------------------------------------------*

TABLES: KNA1,
        TCJ_DOCUMENTS,
        TCJ_POSITIONS,
        ZFIT004.

*--------------------------------------------------------------------*
**Tela de seleção
*--------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS:
  P_BUKRS TYPE TCJ_DOCUMENTS-COMP_CODE OBLIGATORY.

SELECT-OPTIONS:
  S_BZDAT FOR TCJ_POSITIONS-BZDAT,
  S_POSTG FOR TCJ_POSITIONS-POSTING_DATE,
  S_KUNNR FOR KNA1-KUNNR.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-024.

PARAMETERS: P_TODOS RADIOBUTTON GROUP TIP DEFAULT 'X',
            P_COMPE RADIOBUTTON GROUP TIP,
            P_ABERT RADIOBUTTON GROUP TIP.

SELECTION-SCREEN END OF BLOCK B2.

*--------------------------------------------------------------------*
**Conteúdo do relatório:
*--------------------------------------------------------------------*
TYPE-POOLS: SLIS.

TYPES:
  BEGIN OF TY_SAIDA,
    CHECKBOX,
    COMP_CODE       TYPE TCJ_DOCUMENTS-COMP_CODE,
    CAJO_NUMBER     TYPE TCJ_DOCUMENTS-CAJO_NUMBER,
    CAJO_NAME       TYPE TCJ_CJ_NAMES-CAJO_NAME,
    CHECK_NUMBER    TYPE ISCJ_CR_POSTINGS-CHECK_NUMBER,
    CHECK_ISSUER    TYPE ISCJ_CR_POSTINGS-CHECK_ISSUER,
    BANK_KEY        TYPE ISCJ_CR_POSTINGS-BANK_KEY,
    BANK_ACCT       TYPE ISCJ_CR_POSTINGS-BANK_ACCT,
    POSITION_TEXT   TYPE TCJ_POSITIONS-POSITION_TEXT,
    DOCUMENT_DATE   TYPE ISCJ_CR_POSTINGS-DOCUMENT_DATE, " Data no documento
    POSTING_DATE    TYPE ISCJ_CR_POSTINGS-POSTING_DATE,  " Data de lançamento no documento
    BZDAT           TYPE TCJ_POSITIONS-BZDAT,
    CJAMOUNT        TYPE ISCJ_CR_POSTINGS-H_RECEIPTS,
    KUNNR           TYPE KNA1-KUNNR,
    NAME1           TYPE KNA1-NAME1,
    DOCUMENT_NUMBER TYPE ISCJ_CR_POSTINGS-DOCUMENT_NUMBER,
    ALLOC_NMBR      TYPE ISCJ_CR_POSTINGS-ALLOC_NMBR,
    CONTA_DEB       TYPE BSEG-HKONT,
    CONTA_CRE       TYPE BSEG-HKONT,
    STATUS_FB50(5)  TYPE C,
    N_DOC_CRIADO    TYPE BKPF-BELNR,
  END OF TY_SAIDA,

  BEGIN OF TY_TCJ_DOCUMENTS,
    COMP_CODE        TYPE  TCJ_DOCUMENTS-COMP_CODE,
    CAJO_NUMBER      TYPE  TCJ_DOCUMENTS-CAJO_NUMBER,
    FISC_YEAR        TYPE  TCJ_DOCUMENTS-FISC_YEAR,
    POSTING_NUMBER   TYPE  TCJ_DOCUMENTS-POSTING_NUMBER,
    H_RECEIPTS       TYPE  TCJ_DOCUMENTS-H_RECEIPTS,
    H_PAYMENTS       TYPE  TCJ_DOCUMENTS-H_PAYMENTS,
    H_NET_AMOUNT     TYPE  TCJ_DOCUMENTS-H_NET_AMOUNT,
    H_NET_PAYMENT_WT TYPE  TCJ_DOCUMENTS-H_NET_PAYMENT_WT,
    H_TAX_AMOUNT     TYPE  TCJ_DOCUMENTS-H_TAX_AMOUNT,
    DOCUMENT_DATE    TYPE  TCJ_DOCUMENTS-DOCUMENT_DATE,
    DOCUMENT_NUMBER  TYPE  TCJ_DOCUMENTS-DOCUMENT_NUMBER,
    POSTING_DATE     TYPE  TCJ_DOCUMENTS-POSTING_DATE,
    CHECK_NUMBER     TYPE  TCJ_DOCUMENTS-CHECK_NUMBER,
    CHECK_ISSUER     TYPE  TCJ_DOCUMENTS-CHECK_ISSUER,
    BANK_KEY         TYPE  TCJ_DOCUMENTS-BANK_KEY,
    BANK_ACCT        TYPE  TCJ_DOCUMENTS-BANK_ACCT,
    CHECK_FY         TYPE  TCJ_DOCUMENTS-CHECK_FY,
    VALUTA_DATE      TYPE  TCJ_DOCUMENTS-VALUTA_DATE,
  END OF TY_TCJ_DOCUMENTS,

  BEGIN OF TY_TCJ_CHECK_STACKS,
    COMP_CODE       TYPE  TCJ_CHECK_STACKS-COMP_CODE,
    CAJO_NUMBER     TYPE  TCJ_CHECK_STACKS-CAJO_NUMBER,
    FISC_YEAR       TYPE  TCJ_CHECK_STACKS-FISC_YEAR,
    CHECK_STACK     TYPE  TCJ_CHECK_STACKS-CHECK_STACK,
    TRANSACT_NUMBER TYPE  TCJ_CHECK_STACKS-TRANSACT_NUMBER,
    POSTING_DATE    TYPE  TCJ_CHECK_STACKS-POSTING_DATE,
    VALUTA_DATE     TYPE  TCJ_CHECK_STACKS-VALUTA_DATE,
    CHECK_STATUS    TYPE  TCJ_CHECK_STACKS-CHECK_STATUS,
    GL_ACCOUNT      TYPE  TCJ_CHECK_STACKS-GL_ACCOUNT,
  END OF TY_TCJ_CHECK_STACKS,

  BEGIN OF TY_TCJ_POSITIONS,
    COMP_CODE       TYPE  TCJ_POSITIONS-COMP_CODE,
    CAJO_NUMBER     TYPE  TCJ_POSITIONS-CAJO_NUMBER,
    FISC_YEAR       TYPE  TCJ_POSITIONS-FISC_YEAR,
    POSTING_NUMBER  TYPE  TCJ_POSITIONS-POSTING_NUMBER,
    POSITION_NUMBER TYPE  TCJ_POSITIONS-POSITION_NUMBER,
    TRANSACT_NUMBER TYPE  TCJ_POSITIONS-TRANSACT_NUMBER,
    TRANSACT_TYPE   TYPE  TCJ_POSITIONS-TRANSACT_TYPE,
    POSTING_DATE    TYPE  TCJ_POSITIONS-POSTING_DATE,
    GL_ACCOUNT      TYPE  TCJ_POSITIONS-GL_ACCOUNT,
    POSITION_TEXT   TYPE  TCJ_POSITIONS-POSITION_TEXT,
    CUSTOMER        TYPE  TCJ_POSITIONS-CUSTOMER,
    BZDAT           TYPE  TCJ_POSITIONS-BZDAT,
    ALLOC_NMBR      TYPE  TCJ_POSITIONS-ALLOC_NMBR,
  END OF TY_TCJ_POSITIONS,

  BEGIN OF TY_KNA1,
    KUNNR TYPE KNA1-KUNNR,
    NAME1 TYPE KNA1-NAME1,
  END OF TY_KNA1.

*&---------------------------------------------------------------------*
*& Tabela internas / Estrutura                                         *
*&---------------------------------------------------------------------*
DATA: TI_KNA1              TYPE TABLE OF TY_KNA1,
      TI_SAIDA             TYPE TABLE OF TY_SAIDA,
      TI_TCJ_CHECK_STACKS  TYPE TABLE OF TY_TCJ_CHECK_STACKS,
      TI_TCJ_POSITIONS     TYPE TABLE OF TY_TCJ_POSITIONS,
      TI_TCJ_POSITIONS_AUX TYPE TABLE OF TY_TCJ_POSITIONS,
      TI_TCJ_DOCUMENTS     TYPE TABLE OF TY_TCJ_DOCUMENTS,
      TI_TCJ_TRANS_NAMES   TYPE STANDARD TABLE OF TCJ_TRANS_NAMES,
      TI_TCJ_CJ_NAMES      TYPE STANDARD TABLE OF TCJ_CJ_NAMES,

      T_SORT               TYPE SLIS_T_SORTINFO_ALV,
      T_FIELDCAT           TYPE SLIS_T_FIELDCAT_ALV,
      T_EXCLUI             TYPE SLIS_T_EXTAB,
      T_HEADER             TYPE SLIS_T_LISTHEADER,
      T_EVENTS             TYPE SLIS_T_EVENT.

DATA: WA_SAIDA             TYPE TY_SAIDA,
      W_ZFIT004            TYPE ZFIT004,
      WA_TCJ_CHECK_STACKS  TYPE TY_TCJ_CHECK_STACKS,
      WA_TCJ_DOCUMENTS     TYPE TY_TCJ_DOCUMENTS,
      WA_TCJ_POSITIONS     TYPE TY_TCJ_POSITIONS,
      WA_TCJ_POSITIONS_AUX TYPE TY_TCJ_POSITIONS,
      WA_KNA1              TYPE TY_KNA1,
      WA_TCJ_TRANS_NAMES   TYPE TCJ_TRANS_NAMES,
      WA_TCJ_CJ_NAMES      TYPE TCJ_CJ_NAMES,

      W_FIELDCAT           TYPE SLIS_FIELDCAT_ALV,
      W_HEADER             TYPE SLIS_LISTHEADER,
      W_LAYOUT             TYPE SLIS_LAYOUT_ALV,
      W_PRINT              TYPE SLIS_PRINT_ALV,
      LS_GRID_SETTINGS     TYPE LVC_S_GLAY.

DATA: R_VKGRP  TYPE RANGE OF VBAK-VKGRP,
      WR_VKGRP LIKE LINE OF R_VKGRP.

*&---------------------------------------------------------------------*
*& Variáveis                                                           *
*&---------------------------------------------------------------------*
DATA: V_ZLSCH  TYPE C,
      V_COUNTZ TYPE NUM6,
      V_COUNTC TYPE CHAR6,
      V_KUNNR  TYPE KNA1-KUNNR,
      V_NAME1  TYPE KNA1-NAME1,
      V_ZUONR  TYPE NUM10,
      V_BUTXT  TYPE T001-BUTXT.


*&---------------------------------------------------------------------*
*& Constantes                                                          *
*&---------------------------------------------------------------------*
CONSTANTS:
  C_A    TYPE CHAR1   VALUE 'A',
  C_I    TYPE CHAR1   VALUE 'I',
  C_X    TYPE CHAR1   VALUE 'X',
  C_LOGO TYPE BDS_TYPEID  VALUE 'ZLOGO_CACOLA_344_125'. " Logomarca Caçola


*&---------------------------------------------------------------------*
*& Field Symbols                                                       *
*&---------------------------------------------------------------------*
FIELD-SYMBOLS: <F_EVENTS> TYPE SLIS_ALV_EVENT.
